name: Add what is commited
on:
  push:
    branches:
      - main
 
permissions: 
  contents: write

jobs:
  on_merge_or_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run 
        run: echo "This PR was Accepted and Merged!"
      - name: Check and merge
        run: echo ${{github.event.head_commit.message}} >> progress.txt
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@user.noreply.github.com'
          git add progress.txt
          git commit -m "chore: add PR title to commit list [skip ci]"
          git push